# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(362, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.percentageButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("%"))
        self.percentageButton.setGeometry(QtCore.QRect(10, 110, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.percentageButton.setFont(font)
        self.percentageButton.setObjectName("percentageButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("C"))
        self.cButton.setGeometry(QtCore.QRect(100, 110, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.arrowButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.remove_it())
        self.arrowButton.setGeometry(QtCore.QRect(190, 110, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(280, 110, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 200, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(190, 200, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(100, 200, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("*"))
        self.multiplyButton.setGeometry(QtCore.QRect(280, 200, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 290, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(190, 290, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(100, 290, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.subButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("-"))
        self.subButton.setGeometry(QtCore.QRect(280, 290, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.subButton.setFont(font)
        self.subButton.setObjectName("subButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 380, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(190, 380, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(100, 380, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("+"))
        self.addButton.setGeometry(QtCore.QRect(280, 380, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.plusMinusButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.plus_minus_it())
        self.plusMinusButton.setGeometry(QtCore.QRect(10, 470, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plusMinusButton.setFont(font)
        self.plusMinusButton.setObjectName("plusMinusButton")
        self.dotButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.dot_it())
        self.dotButton.setGeometry(QtCore.QRect(190, 470, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.dotButton.setFont(font)
        self.dotButton.setObjectName("dotButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(100, 470, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.math_it())
        self.equalButton.setGeometry(QtCore.QRect(280, 470, 70, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 362, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    #remove character
    def remove_it(self):
        # grab whats on the screen already
        screen = self.outputLabel.text()
        #remove last item in list/string
        screen = screen[:-1]
        #Output back to the screen
        self.outputLabel.setText(screen)

    #lets do some math!
    def math_it(self):
        #grab what's on the screen already
        screen = self.outputLabel.text()
        try:
            #do the math (python built_in func)
            answer = eval(screen)
            #output answer to the screen
            self.outputLabel.setText(str(answer))
        except:
            #output error to the screen
            self.outputLabel.setText("ERROR")


    # Change from postive/negative
    def plus_minus_it(self):
        #garb whatever is on the screen already
        screen = self.outputLabel.text()
        if "-" in screen:
            if screen[0]=="-":
                self.outputLabel.setText(screen.replace("-",""))
            else: 
                self.outputLabel.setText(screen.replace("-","+"))
        else:
            #if "+" in screen:
                #self.outputLabel.setText(screen.replace("+","-"))
            self.outputLabel.setText(f'-{screen}')
           
                
    
    #add a decimal
    def dot_it(self):
        screen = self.outputLabel.text()
    
        if screen[-1]==".":
            pass
        else:
            self.outputLabel.setText(f'{screen}.')


    def press_it(self, pressed):
        if pressed=="C":
            self.outputLabel.setText("0")
        else:
            #check to see if starts with 0 and delete 0
            if self.outputLabel.text() =="0":
                self.outputLabel.setText("")
            #otherwise concatanate the pressed button with what was there already
            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.percentageButton.setText(_translate("MainWindow", "%"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.arrowButton.setText(_translate("MainWindow", "DEL"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.multiplyButton.setText(_translate("MainWindow", "*"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.subButton.setText(_translate("MainWindow", "-"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.addButton.setText(_translate("MainWindow", "+"))
        self.plusMinusButton.setText(_translate("MainWindow", "+/-"))
        self.dotButton.setText(_translate("MainWindow", "."))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.equalButton.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
