# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from connect2 import Ui_SecondWindow

class Ui_MainWindow(object):
    def open_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SecondWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def clicker(self):
        #grab the text from  line edit
        thing= self.lineEdit.text()
        #pass that to the label in second window 
        #as we have already access to 2nd window which we had open using open window we will just change the label in the second window
        self.ui.label.setText(thing)

    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 20, 481, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicker())
        self.submit_button.setGeometry(QtCore.QRect(50, 310, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.open_window_button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.open_window())
        self.open_window_button.setGeometry(QtCore.QRect(50, 390, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.open_window_button.setFont(font)
        self.open_window_button.setObjectName("open_window_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT"))
        self.open_window_button.setText(_translate("MainWindow", "OPEN WINDOW"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
