# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(245, 220)
        self.dial = QtWidgets.QDial(Form)
        #Set Minimum and maximum value
        #self.dial.setMinimum(20)
        #self.dial.setMaximum(500)
        self.dial.setRange(1,100)

        #Set default value
        self.dial.setValue(50)

        #add notches
        self.dial.setNotchesVisible(True)

        #set Color
        self.dial.setStyleSheet('background-color:#233981')

        #Use Dial
        self.dial.valueChanged.connect(lambda: self.dialer())

        self.dial.setGeometry(QtCore.QRect(40, 30, 141, 121))
        self.dial.setObjectName("dial")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 160, 180, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", f'Current Value: {str(self.dial.value())}'))

    def dialer(self):
        #grab the current value of dialer
        value=self.dial.value()
        #show that using changing the label
        self.label.setText(f'Current Value: {str(value)}')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
