# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todoList.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addItem_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.addItem_lineEdit.setGeometry(QtCore.QRect(20, 20, 571, 51))
        self.addItem_lineEdit.setObjectName("addItem_lineEdit")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.add_it())
        self.addButton.setGeometry(QtCore.QRect(20, 90, 181, 41))
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.delete_it())
        self.deleteButton.setGeometry(QtCore.QRect(220, 90, 181, 41))
        self.deleteButton.setObjectName("deleteButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.clear_it())
        self.clearButton.setGeometry(QtCore.QRect(420, 90, 171, 41))
        self.clearButton.setObjectName("clearButton")
        self.myList_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.myList_listWidget.setGeometry(QtCore.QRect(20, 150, 571, 361))
        self.myList_listWidget.setObjectName("myList_listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 612, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #add item to list
    def add_it(self):
        #grab item from listbox
        item=self.addItem_lineEdit.text()

        #add item to list
        self.myList_listWidget.addItem(item)

        #clear the item box
        self.addItem_lineEdit.setText("")

    #Delete item from list
    def delete_it(self):
        #Grab the select row or current row
        clicked = self.myList_listWidget.currentRow()

        #delete selected row
        self.myList_listWidget.takeItem(clicked)


    #Clear all items from list
    def clear_it(self):
        self.myList_listWidget.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To do List"))
        self.addButton.setText(_translate("MainWindow", "Add Item"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Item"))
        self.clearButton.setText(_translate("MainWindow", "Clear List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
